name: Documentation

on:
  push:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  find_files:
    runs-on: ubuntu-latest
    
    outputs:
      matrix: ${{ steps.files.outputs.matrix }}
      artifact_name: ${{ steps.artifact_data.outputs.artifact_name }}
      artifact_path: ${{ steps.artifact_data.outputs.artifact_path }}

    steps:
      - uses: actions/checkout@v2

      - name: Find files and create matrix
        id: files
        run: |
          matrix=`python3 ./.github/find-and-stop.py .`
          echo "##[set-output name=matrix;]$matrix"
          
      - name: Generate name and path of artifact
        id: artifact_data
        run: |
          artifact_data=`python3 ./.github/artifact-data.py '${{ steps.files.outputs.matrix }}'`
          artifact_name=`echo $artifact_data | jq -r ".name"`
          artifact_path=`echo $artifact_data | jq -r ".path"`
          
          echo $artifact_name
          echo $artifact_path
          
          echo "##[set-output name=artifact_name;]$artifact_name"
          echo "##[set-output name=artifact_path;]$artifact_path"
            
  compile_files:
    runs-on: ubuntu-latest
    needs: [ find_files ]
    strategy:
      matrix: ${{fromJson(needs.find_files.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
        
      - name: Compile tex files into pdf
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ${{ matrix.working_directory }}
          root_file: ${{ matrix.filename }}
          post_compile: "latexmk -c"
          latexmk_shell_escape: true
          
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ needs.find_files.outputs.artifact_name }}
          path: |
            ${{ github.workspace }}/${{ needs.find_files.outputs.artifact_path }}/**/*.pdf
